### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by rcemper** [lscalese/isc-webgateway-letsencrypt#1]
ERROR: failed to solve: intersystems/webgateway:2020.3.0.221.0: pull access denied, repository does not exist or m
ay require authorization: server message: insufficient_scope: authorization failed

**Comment by lscalese** [comment]
Thank you for your report @rcemper , I'll fix it as soon as possible (after the Global Summit).

**Comment by lscalese** [comment]
Hi @rcemper ,

Indeed the image `intersystems/webgateway:2020.3.0.221.0` is not available and it seems the Webgateway is not available in the public registry.

I changed the image name to `containers.intersystems.com/intersystems/webgateway:2023.1.0.235.1` but it needs to be logged in to containers.intersystems.com.  The readme file has been updated.  

This problem will occur again, because we can't use the `latest` tag, unfortunately.

**Comment by rcemper** [comment]
thanks for checking.
I tried it myself and ended with the same result.
so this may pop up at some time in the future.

**Comment by rcemper** [comment]
thanks for checking.
I tried it myself and ended with the same result.
so this may pop up at some time in the future.

**Comment by lscalese** [comment]
> I tried it myself and ended with the same result.

Were you connected in with: 
```
docker login -u="your email" -p="your token" containers.intersystems.com
```

To retrieve the token [SSO.UI.User.ApplicationTokens.cls](https://login.intersystems.com/login/SSO.UI.User.ApplicationTokens.cls)

**Comment by rcemper** [comment]
**same result** referred to the previous variant.
I'll try the new later this week.

**Comment by lscalese** [comment]
Ok, I quickly perform a build and I don't have any problem to pull the image `containers.intersystems.com/intersystems/webgateway:2023.1.0.235.1` as long I'm logged to the registry.
However...the [line](https://github.com/lscalese/isc-webgateway-letsencrypt/blob/master/Dockerfile#L3) : 
```
RUN /configHttpd.sh
```
result to : 

```
------
 > [2/9] RUN /configHttpd.sh:
#5 0.330 /bin/bash: /configHttpd.sh: No such file or directory
------
```

Probably this file does not exist in the new WebGateway version.  I noticed that I don't run this in other projects, so we don't longer need it (it's now deleted).
